### ISSUE TITLE
Custom Buttons

### ISSUE THREAD

**Issue by notknightsbridge** [notknightsbridge/notknightsbridge.github.io#3]
http://charliepark.org/bootstrap_buttons/

**Comment by notknightsbridge** [comment]
```css
/* http://charliepark.org/bootstrap_buttons/ */
/* Source color: #1462D8 */
.btn-primary-custom {
  
  background-color: hsl(216, 83%, 57%) !important;
  
  background-repeat: repeat-x;
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#a6c6f6", endColorstr="#367fec");
  
  background-image: -khtml-gradient(linear, left top, left bottom, from(#a6c6f6), to(#367fec));
  background-image: -moz-linear-gradient(top, #a6c6f6, #367fec);
  background-image: -ms-linear-gradient(top, #a6c6f6, #367fec);
  background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #a6c6f6), color-stop(100%, #367fec));
  background-image: -webkit-linear-gradient(top, #a6c6f6, #367fec);
  background-image: -o-linear-gradient(top, #a6c6f6, #367fec);
  background-image: linear-gradient(#a6c6f6, #367fec);
  
  border-color: #367fec #367fec hsl(216, 83%, 51%);
  
  color: #333 !important;
  
  text-shadow: 0 1px 1px rgba(255, 255, 255, 0.39);

  -webkit-font-smoothing: antialiased;
}
```
